import { defaultRng, randomInt, shuffle } from '@/shared/lib/random'
import type { Rng } from '@/shared/lib/random'

export type WordTheme =
  | 'nourriture'
  | 'boissons'
  | 'objets'
  | 'maison'
  | 'lieux'
  | 'nature'
  | 'sport'
  | 'culture'
  | 'metiers'
  | 'transports'
  | 'corps'
  | 'mode'
  | 'tech'
  | 'social'
  | 'abstrait'

export interface WordPair {
  id: string
  civil: string
  undercover: string
  theme: WordTheme
}

export const THEME_LABELS: Record<WordTheme, string> = {
  nourriture: 'Nourriture',
  boissons: 'Boissons',
  objets: 'Objets',
  maison: 'Maison',
  lieux: 'Lieux',
  nature: 'Nature & animaux',
  sport: 'Sport',
  culture: 'Culture & loisirs',
  metiers: 'Métiers',
  transports: 'Transports',
  corps: 'Corps & santé',
  mode: 'Mode',
  tech: 'Technologie',
  social: 'Vie sociale',
  abstrait: 'Notions',
}

/**
 * Calibrage de chaque paire, appliqué sans exception :
 *  — les deux mots appartiennent à la même famille et partagent au moins deux
 *    attributs descriptibles (usage, lieu, forme) ;
 *  — ils divergent sur au moins un attribut net dès qu'on creuse ;
 *  — pas de synonymes (« stress » / « anxiété » : indiscernables, donc injouable),
 *    pas de mot générique face à son propre exemple (« chien » / « animal »),
 *    pas d'écart tel que l'undercover se grille à sa première description
 *    (« chocolat » / « sel »).
 */
const RAW_PAIRS: Record<WordTheme, readonly (readonly [string, string])[]> = {
  nourriture: [
    ['Pizza', 'Quiche'],
    ['Crêpe', 'Gaufre'],
    ['Croissant', 'Pain au chocolat'],
    ['Hamburger', 'Kebab'],
    ['Sushi', 'Nem'],
    ['Lasagnes', 'Gratin'],
    ['Purée', 'Frites'],
    ['Riz', 'Semoule'],
    ['Baguette', 'Brioche'],
    ['Yaourt', 'Compote'],
    ['Confiture', 'Miel'],
    ['Ketchup', 'Mayonnaise'],
    ['Moutarde', 'Piment'],
    ['Steak', 'Saucisse'],
    ['Poulet rôti', 'Jambon'],
    ['Omelette', 'Soufflé'],
    ['Soupe', 'Ragoût'],
    ['Salade', 'Taboulé'],
    ['Chips', 'Popcorn'],
    ['Cacahuète', 'Olive'],
    ['Glace', 'Chantilly'],
    ['Gâteau', 'Tarte'],
    ['Cookie', 'Madeleine'],
    ['Chocolat', 'Nougat'],
    ['Bonbon', 'Chewing-gum'],
    ['Fromage', 'Beurre'],
    ['Œuf', 'Lait'],
    ['Spaghetti', 'Ravioli'],
    ['Barbecue', 'Raclette'],
    ['Sandwich', 'Wrap'],
    ['Tarte', 'Clafoutis'],
    ['Pain de mie', 'Biscotte'],
    ['Beignet', 'Churros'],
    ['Frites', 'Nuggets'],
    ['Camembert', 'Mozzarella'],
    ['Saucisson', 'Pâté'],
    ["Sirop d'érable", 'Caramel'],
    ['Crème fraîche', "Huile d'olive"],
    ['Kiwi', 'Ananas'],
    ['Pomme', 'Poire'],
    ['Fraise', 'Cerise'],
    ['Carotte', 'Betterave'],
    ['Tomate', 'Courgette'],
    ['Poivron', 'Aubergine'],
  ],
  boissons: [
    ['Café', 'Thé'],
    ['Bière', 'Cidre'],
    ['Vin rouge', 'Champagne'],
    ['Whisky', 'Rhum'],
    ['Limonade', 'Sirop'],
    ["Jus d'orange", 'Smoothie'],
    ['Eau minérale', 'Tisane'],
    ['Chocolat chaud', 'Cappuccino'],
    ['Cocktail', 'Shot'],
    ['Vodka', 'Tequila'],
    ['Milkshake', 'Yaourt à boire'],
    ['Soda', 'Boisson énergisante'],
    ['Punch', 'Sangria'],
    ['Apéritif', 'Digestif'],
    ['Thé glacé', 'Citronnade'],
    ['Rosé', 'Vin blanc'],
    ['Gin', 'Cognac'],
    ['Kir', 'Mojito'],
    ['Eau de coco', 'Jus de pomme'],
    ['Bubble tea', 'Frappé'],
  ],
  objets: [
    ['Parapluie', 'Casquette'],
    ['Montre', 'Bracelet'],
    ['Clé', 'Cadenas'],
    ['Portefeuille', 'Trousse'],
    ['Stylo', 'Crayon'],
    ['Cahier', 'Agenda'],
    ['Ciseaux', 'Cutter'],
    ['Colle', 'Scotch'],
    ['Bougie', 'Lampe torche'],
    ['Miroir', 'Loupe'],
    ['Sac à dos', 'Valise'],
    ['Peigne', 'Rasoir'],
    ['Savon', 'Dentifrice'],
    ['Serviette', 'Nappe'],
    ['Balai', 'Aspirateur'],
    ['Éponge', 'Serpillière'],
    ['Poubelle', 'Panier à linge'],
    ['Boîte aux lettres', 'Coffre-fort'],
    ['Bouteille', 'Canette'],
    ['Allumette', 'Briquet'],
    ['Corde', 'Chaîne'],
    ['Marteau', 'Tournevis'],
    ['Torchon', 'Gant de cuisine'],
    ['Cintre', 'Panier'],
    ['Tirelire', 'Coffret'],
    ['Aiguille', 'Punaise'],
    ['Règle', 'Compas'],
    ['Gomme', 'Taille-crayon'],
    ['Pince à linge', 'Trombone'],
    ['Bocal', 'Thermos'],
    ['Échelle', 'Brouette'],
    ['Clé à molette', 'Perceuse'],
    ['Cadre photo', 'Vase'],
  ],
  maison: [
    ['Canapé', 'Fauteuil'],
    ['Lit', 'Hamac'],
    ['Table', 'Bureau'],
    ['Chaise', 'Tabouret'],
    ['Armoire', 'Commode'],
    ['Étagère', 'Coffre'],
    ['Rideau', 'Store'],
    ['Tapis', 'Paillasson'],
    ['Cheminée', 'Radiateur'],
    ['Baignoire', 'Douche'],
    ['Lave-vaisselle', 'Machine à laver'],
    ['Four', 'Micro-ondes'],
    ['Frigo', 'Placard'],
    ['Escalier', 'Ascenseur'],
    ['Balcon', 'Véranda'],
    ['Cave', 'Grenier'],
    ['Porte', 'Fenêtre'],
    ['Garage', 'Abri de jardin'],
    ['Cuisine', 'Salle de bain'],
    ['Jardin', 'Piscine'],
    ['Matelas', 'Couette'],
    ['Oreiller', 'Plaid'],
    ['Lampadaire', 'Applique'],
    ['Plafond', 'Plancher'],
    ['Mur', 'Toit'],
    ['Poêle à bois', 'Climatiseur'],
    ['Terrasse', 'Cour'],
    ['Buanderie', 'Dressing'],
    ['Sonnette', 'Judas'],
    ['Volet', 'Moustiquaire'],
    ['Robinet', 'Pommeau de douche'],
  ],
  lieux: [
    ['Cinéma', 'Théâtre'],
    ['Bibliothèque', 'Musée'],
    ['Hôpital', 'Pharmacie'],
    ['École', 'Université'],
    ['Restaurant', 'Cantine'],
    ['Bar', 'Boîte de nuit'],
    ['Hôtel', 'Camping'],
    ['Plage', 'Lac'],
    ['Montagne', 'Désert'],
    ['Forêt', 'Parc'],
    ['Supermarché', 'Marché'],
    ['Boulangerie', 'Boucherie'],
    ['Aéroport', 'Gare'],
    ['Église', 'Château'],
    ['Stade', 'Gymnase'],
    ['Zoo', 'Aquarium'],
    ['Prison', 'Commissariat'],
    ['Banque', 'Bureau de poste'],
    ['Coiffeur', 'Tatoueur'],
    ['Station-service', 'Péage'],
    ['Ferme', 'Vignoble'],
    ['Île', 'Volcan'],
    ['Village', 'Banlieue'],
    ['Grotte', 'Tunnel'],
    ['Piscine municipale', 'Patinoire'],
    ['Salle de concert', 'Salle des fêtes'],
    ['Casino', 'Hippodrome'],
    ['Cimetière', 'Monument aux morts'],
    ['Mairie', 'Tribunal'],
    ['Caserne', 'Gendarmerie'],
    ['Auberge de jeunesse', "Chambre d'hôtes"],
    ['Port', 'Phare'],
    ['Verger', 'Serre'],
    ['Marché de Noël', 'Brocante'],
    ['Aire de jeux', 'Skatepark'],
  ],
  nature: [
    ['Chien', 'Loup'],
    ['Chat', 'Renard'],
    ['Cheval', 'Âne'],
    ['Vache', 'Chèvre'],
    ['Poule', 'Canard'],
    ['Cochon', 'Sanglier'],
    ['Lapin', 'Écureuil'],
    ['Souris', 'Taupe'],
    ['Lion', 'Ours'],
    ['Éléphant', 'Hippopotame'],
    ['Girafe', 'Autruche'],
    ['Singe', 'Perroquet'],
    ['Serpent', 'Lézard'],
    ['Grenouille', 'Tortue'],
    ['Requin', 'Dauphin'],
    ['Baleine', 'Pieuvre'],
    ['Poisson rouge', 'Méduse'],
    ['Abeille', 'Fourmi'],
    ['Papillon', 'Libellule'],
    ['Araignée', 'Scorpion'],
    ['Aigle', 'Pigeon'],
    ['Manchot', 'Phoque'],
    ['Chameau', 'Kangourou'],
    ['Rose', 'Tournesol'],
    ['Chêne', 'Sapin'],
    ['Cactus', 'Bambou'],
    ['Pluie', 'Neige'],
    ['Orage', 'Brouillard'],
    ['Rivière', 'Cascade'],
    ['Océan', 'Étang'],
    ['Sable', 'Boue'],
    ['Champignon', 'Mousse'],
    ['Cerf', 'Bison'],
    ['Hérisson', 'Blaireau'],
    ['Chauve-souris', 'Hibou'],
    ['Corbeau', 'Mouette'],
    ['Cygne', 'Flamant rose'],
    ['Crocodile', 'Varan'],
    ['Panda', 'Koala'],
    ['Zèbre', 'Antilope'],
    ['Escargot', 'Ver de terre'],
    ['Guêpe', 'Moustique'],
    ['Crabe', 'Étoile de mer'],
    ['Tulipe', 'Orchidée'],
    ['Palmier', 'Saule'],
    ['Vent', 'Grêle'],
    ['Arc-en-ciel', 'Éclipse'],
    ['Rocher', 'Falaise'],
  ],
  sport: [
    ['Football', 'Rugby'],
    ['Basket', 'Handball'],
    ['Tennis', 'Badminton'],
    ['Golf', 'Pétanque'],
    ['Natation', 'Plongée'],
    ['Ski', 'Luge'],
    ['Patinage', 'Escalade'],
    ['Boxe', 'Judo'],
    ['Marathon', 'Triathlon'],
    ['Vélo', 'Trottinette'],
    ['Yoga', 'Musculation'],
    ['Danse', 'Gymnastique'],
    ['Surf', 'Voile'],
    ['Équitation', 'Rodéo'],
    ["Tir à l'arc", 'Fléchettes'],
    ['Bowling', 'Billard'],
    ['Escrime', 'Karaté'],
    ['Volley', 'Ping-pong'],
    ['Course à pied', 'Randonnée'],
    ['Aviron', 'Water-polo'],
    ['Médaille', 'Trophée'],
    ['Arbitre', 'Entraîneur'],
    ['Squash', 'Padel'],
    ['Plongeon', 'Nage synchronisée'],
    ['Saut en longueur', 'Course de haies'],
    ['Lutte', 'Sumo'],
    ['Football américain', 'Baseball'],
    ['Cricket', 'Hockey sur gazon'],
    ['Motocross', 'Rallye'],
    ['Alpinisme', 'Spéléologie'],
    ['Parapente', 'Saut en parachute'],
    ['Crossfit', 'Aquagym'],
    ['Supporter', 'Commentateur'],
  ],
  culture: [
    ['Livre', 'Magazine'],
    ['Film', 'Série'],
    ['Concert', 'Festival'],
    ['Guitare', 'Violon'],
    ['Piano', 'Batterie'],
    ['Peinture', 'Sculpture'],
    ['Photo', 'Dessin'],
    ['Opéra', 'Comédie musicale'],
    ['Jeu vidéo', 'Jeu de société'],
    ['Échecs', 'Poker'],
    ['Puzzle', 'Mots croisés'],
    ['Karaoké', 'Stand-up'],
    ['Cirque', "Parc d'attractions"],
    ['Magie', 'Marionnettes'],
    ['Roman', 'Bande dessinée'],
    ['Podcast', 'Radio'],
    ['Documentaire', 'Journal télévisé'],
    ["Feu d'artifice", 'Défilé'],
    ['Chorale', 'Fanfare'],
    ['Tatouage', 'Piercing'],
    ['Fresque', 'Mosaïque'],
    ['Ballet', 'Cabaret'],
    ['Poème', 'Fable'],
    ["Galerie d'art", 'Vitrine'],
    ['Exposition', 'Conférence'],
    ['Vinyle', 'Cassette'],
    ['Trompette', 'Accordéon'],
    ['Flûte', 'Harpe'],
    ['Court-métrage', 'Publicité'],
    ['Manga', 'Comics'],
    ['Jeu de rôle', 'Escape game'],
    ['Sudoku', 'Loto'],
  ],
  metiers: [
    ['Médecin', 'Vétérinaire'],
    ['Infirmier', 'Pompier'],
    ['Policier', 'Garde du corps'],
    ['Professeur', 'Bibliothécaire'],
    ['Boulanger', 'Cuisinier'],
    ['Serveur', 'Barman'],
    ['Coiffeur', 'Fleuriste'],
    ['Avocat', 'Notaire'],
    ['Juge', 'Journaliste'],
    ['Architecte', 'Ingénieur'],
    ['Plombier', 'Électricien'],
    ['Menuisier', 'Maçon'],
    ['Agriculteur', 'Pêcheur'],
    ['Pilote', 'Steward'],
    ['Chauffeur de taxi', 'Livreur'],
    ['Astronaute', 'Explorateur'],
    ['Acteur', 'Chanteur'],
    ['Photographe', 'Styliste'],
    ['Comptable', 'Banquier'],
    ['Vendeur', 'Agent immobilier'],
    ['Militaire', 'Marin'],
    ['Facteur', 'Éboueur'],
    ['Dentiste', 'Ophtalmologue'],
    ['Psychologue', 'Coach sportif'],
    ['Chirurgien', 'Kinésithérapeute'],
    ['Sage-femme', 'Pédiatre'],
    ['Pharmacien', 'Opticien'],
    ['Pâtissier', 'Traiteur'],
    ['Libraire', 'Éditeur'],
    ['Traducteur', 'Écrivain'],
    ['Informaticien', 'Graphiste'],
    ['Mécanicien', 'Soudeur'],
    ['Jardinier', 'Bûcheron'],
    ['Berger', 'Apiculteur'],
    ['Guide touristique', 'Réceptionniste'],
    ['Douanier', 'Pompiste'],
  ],
  transports: [
    ['Voiture', 'Camion'],
    ['Vélo', 'Moto'],
    ['Train', 'Métro'],
    ['Bus', 'Tramway'],
    ['Avion', 'Hélicoptère'],
    ['Bateau', 'Sous-marin'],
    ['Fusée', 'Satellite'],
    ['Taxi', 'Ambulance'],
    ['Trottinette', 'Skateboard'],
    ['Montgolfière', 'Parachute'],
    ['Téléphérique', 'Tapis roulant'],
    ['Autoroute', 'Rond-point'],
    ['Feu rouge', 'Panneau stop'],
    ['Ceinture de sécurité', 'Airbag'],
    ['Permis de conduire', 'Carte grise'],
    ['Camping-car', 'Tente'],
    ['Camionnette', 'Tracteur'],
    ['Scooter', 'Quad'],
    ['Funiculaire', 'Navette'],
    ['Ferry', 'Voilier'],
    ['Planeur', 'Dirigeable'],
    ['Passage piéton', 'Trottoir'],
    ['Coffre', 'Rétroviseur'],
    ['Essence', 'Recharge électrique'],
    ['Bagage à main', 'Soute'],
  ],
  corps: [
    ['Cheveux', 'Barbe'],
    ['Main', 'Pied'],
    ['Œil', 'Oreille'],
    ['Dent', 'Ongle'],
    ['Cœur', 'Poumon'],
    ['Cerveau', 'Estomac'],
    ['Muscle', 'Os'],
    ['Rhume', 'Migraine'],
    ['Fièvre', 'Allergie'],
    ['Vaccin', 'Pansement'],
    ['Sommeil', 'Rêve'],
    ['Éternuement', 'Hoquet'],
    ['Sourire', "Clin d'œil"],
    ['Larme', 'Sueur'],
    ['Bâillement', 'Frisson'],
    ['Genou', 'Coude'],
    ['Épaule', 'Hanche'],
    ['Doigt', 'Orteil'],
    ['Nez', 'Bouche'],
    ['Peau', 'Poil'],
    ['Foie', 'Rein'],
    ['Sang', 'Salive'],
    ['Toux', 'Courbature'],
    ['Cicatrice', 'Bleu'],
    ['Sieste', 'Insomnie'],
  ],
  mode: [
    ['Pantalon', 'Short'],
    ['Jupe', 'Robe'],
    ['Chemise', 'T-shirt'],
    ['Pull', 'Veste'],
    ['Manteau', 'Imperméable'],
    ['Basket', 'Sandale'],
    ['Botte', 'Chausson'],
    ['Chaussette', 'Collant'],
    ['Écharpe', 'Gant'],
    ['Bonnet', 'Chapeau'],
    ['Cravate', 'Bretelles'],
    ['Ceinture', 'Sac à main'],
    ['Lunettes', 'Lentilles'],
    ['Bague', 'Collier'],
    ['Maillot de bain', 'Pyjama'],
    ['Costume', 'Déguisement'],
    ['Parfum', 'Vernis à ongles'],
    ['Sweat', 'Gilet'],
    ['Jean', 'Salopette'],
    ['Débardeur', 'Polo'],
    ['Escarpin', 'Mocassin'],
    ['Casquette', 'Béret'],
    ["Boucle d'oreille", 'Broche'],
    ['Rouge à lèvres', 'Mascara'],
    ['Peignoir', 'Combinaison'],
  ],
  tech: [
    ['Téléphone', 'Tablette'],
    ['Ordinateur', 'Console de jeu'],
    ['Télévision', 'Vidéoprojecteur'],
    ['Casque audio', 'Enceinte'],
    ['Appareil photo', 'Drone'],
    ['Imprimante', 'Scanner'],
    ['Clavier', 'Manette'],
    ['Wi-Fi', 'Bluetooth'],
    ['Email', 'SMS'],
    ['Mot de passe', 'Empreinte digitale'],
    ['Application', 'Site web'],
    ['Réveil', 'Minuteur'],
    ['GPS', 'Boussole'],
    ['Robot', 'Intelligence artificielle'],
    ['Batterie', 'Chargeur'],
    ['Clé USB', 'Disque dur'],
    ['Écran tactile', 'Télécommande'],
    ['Souris', 'Webcam'],
    ['Micro', 'Trépied'],
    ['Liseuse', 'Montre connectée'],
    ['Carte SIM', 'Carte bancaire'],
    ['Antivirus', 'Sauvegarde'],
    ['Streaming', 'Téléchargement'],
    ['Code source', 'Base de données'],
    ['Casque VR', 'Console portable'],
    ['Panneau solaire', 'Éolienne'],
  ],
  social: [
    ['Anniversaire', 'Mariage'],
    ['Noël', 'Nouvel An'],
    ['Halloween', 'Carnaval'],
    ['Baptême', 'Enterrement de vie de garçon'],
    ['Cadeau', 'Carte postale'],
    ['Invitation', 'Faire-part'],
    ['Apéro', 'Brunch'],
    ['Pique-nique', 'Buffet'],
    ['Toast', 'Discours'],
    ['Bougie', 'Confettis'],
    ['Photo de groupe', 'Selfie'],
    ['Colocation', 'Voisinage'],
    ['Rendez-vous', 'Réunion'],
    ['Vacances', 'Week-end'],
    ['Déménagement', 'Voyage'],
    ['Premier rendez-vous', 'Rupture'],
    ['Coup de foudre', 'Amitié'],
    ['Ragot', 'Secret'],
    ['Blague', 'Canular'],
    ['Réveillon', 'Crémaillère'],
    ['Fiançailles', 'Divorce'],
    ['Baby shower', 'Départ à la retraite'],
    ['Fête foraine', 'Bal'],
    ['Remise de diplôme', 'Cérémonie'],
    ['Voisin', 'Collègue'],
    ['Groupe de discussion', 'Appel vidéo'],
    ['Carte de vœux', 'Lettre manuscrite'],
    ['Compliment', 'Reproche'],
  ],
  abstrait: [
    ['Courage', 'Fierté'],
    ['Jalousie', 'Curiosité'],
    ['Patience', 'Discipline'],
    ['Chance', 'Destin'],
    ['Mensonge', 'Excuse'],
    ['Promesse', 'Pari'],
    ['Rêve', 'Souvenir'],
    ['Silence', 'Solitude'],
    ['Routine', 'Tradition'],
    ['Liberté', 'Pouvoir'],
    ['Justice', 'Vengeance'],
    ['Peur', 'Surprise'],
    ['Ennui', 'Fatigue'],
    ['Ambition', 'Talent'],
    ['Réputation', 'Charisme'],
    ['Regret', 'Nostalgie'],
    ['Colère', 'Impatience'],
    ['Confiance', 'Respect'],
    ['Honte', 'Timidité'],
    ['Espoir', 'Illusion'],
    ['Loyauté', 'Obéissance'],
    ['Imagination', 'Intuition'],
    ['Sacrifice', 'Effort'],
    ['Pardon', 'Oubli'],
    ['Rivalité', 'Méfiance'],
    ['Sagesse', 'Expérience'],
    ['Coïncidence', 'Superstition'],
  ],
}

function slug(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

export const WORD_PAIRS: readonly WordPair[] = Object.entries(RAW_PAIRS).flatMap(
  ([theme, pairs]) =>
    pairs.map(([civil, undercover]) => ({
      id: `${theme}-${slug(civil)}`,
      civil,
      undercover,
      theme: theme as WordTheme,
    })),
)

export const ALL_THEMES = Object.keys(RAW_PAIRS) as WordTheme[]

export function pairsForThemes(themes: readonly WordTheme[]): WordPair[] {
  if (themes.length === 0) return [...WORD_PAIRS]
  return WORD_PAIRS.filter((pair) => themes.includes(pair.theme))
}

export function countByTheme(theme: WordTheme): number {
  return WORD_PAIRS.filter((pair) => pair.theme === theme).length
}

/**
 * Tire une paire non encore jouée. Le sens est tiré au sort à chaque partie :
 * sans ça, le mot le plus « évident » de la paire serait toujours celui des
 * civils, et les habitués finiraient par le savoir.
 */
export function drawPair(
  pool: readonly WordPair[],
  usedIds: readonly string[],
  rng: Rng = defaultRng,
): WordPair | null {
  const available = pool.filter((pair) => !usedIds.includes(pair.id))
  const candidates = available.length > 0 ? available : pool
  if (candidates.length === 0) return null
  const drawn = shuffle(candidates, rng)[0] as WordPair
  const swap = randomInt(2, rng) === 1
  return swap ? { ...drawn, civil: drawn.undercover, undercover: drawn.civil } : drawn
}
