export type GuessCategory =
  | 'general'
  | 'celebrites'
  | 'films'
  | 'chansons'
  | 'sport'
  | 'nourriture'
  | 'lieux'
  | 'expressions'

export interface GuessCard {
  id: string
  text: string
  category: GuessCategory
  /** Mots bannis en manche « Interdit ». */
  taboo?: string[]
}

export const CATEGORY_LABELS: Record<GuessCategory, string> = {
  general: 'Objets & quotidien',
  celebrites: 'Célébrités',
  films: 'Films & séries',
  chansons: 'Chansons',
  sport: 'Sport',
  nourriture: 'Nourriture',
  lieux: 'Lieux célèbres',
  expressions: 'Expressions',
}

/** Seule cette catégorie porte des mots interdits : c'est le paquet « Interdit ». */
const GENERAL: readonly (readonly [string, [string, string, string]])[] = [
  ['Pizza', ['italienne', 'four', 'fromage']],
  ['Plage', ['sable', 'mer', 'vacances']],
  ['Ordinateur', ['clavier', 'écran', 'bureau']],
  ['Chien', ['aboyer', 'os', 'laisse']],
  ['Guitare', ['cordes', 'musique', 'jouer']],
  ['Voiture', ['route', 'conduire', 'roues']],
  ['Café', ['boire', 'matin', 'tasse']],
  ['Médecin', ['hôpital', 'malade', 'soigner']],
  ['Anniversaire', ['gâteau', 'bougies', 'cadeau']],
  ['Neige', ['froid', 'blanc', 'hiver']],
  ['Téléphone', ['appeler', 'portable', 'écran']],
  ['École', ['élèves', 'professeur', 'cours']],
  ['Mariage', ['robe', 'église', 'couple']],
  ['Avion', ['voler', 'aéroport', 'ciel']],
  ['Football', ['ballon', 'but', 'équipe']],
  ['Cuisine', ['manger', 'plat', 'casserole']],
  ['Livre', ['lire', 'pages', 'roman']],
  ['Montagne', ['ski', 'altitude', 'sommet']],
  ['Chat', ['miauler', 'souris', 'félin']],
  ['Pluie', ['eau', 'parapluie', 'mouillé']],
  ['Piano', ['touches', 'musique', 'noires']],
  ['Vélo', ['pédales', 'roues', 'guidon']],
  ['Boulangerie', ['pain', 'croissant', 'baguette']],
  ['Ascenseur', ['étage', 'monter', 'bouton']],
  ['Plombier', ['tuyau', 'fuite', 'eau']],
  ['Hôpital', ['malade', 'médecin', 'lit']],
  ["Feu d'artifice", ['ciel', 'explosion', 'juillet']],
  ['Pharmacie', ['médicament', 'croix', 'verte']],
  ['Miroir', ['reflet', 'voir', 'salle de bain']],
  ['Bibliothèque', ['livres', 'silence', 'emprunter']],
  ['Parapluie', ['pluie', 'ouvrir', 'mouillé']],
  ['Aspirateur', ['ménage', 'poussière', 'brancher']],
  ['Barbecue', ['viande', 'été', 'jardin']],
  ['Camping', ['tente', 'nature', 'dormir']],
  ['Chocolat', ['cacao', 'sucré', 'tablette']],
  ['Facteur', ['courrier', 'boîte', 'lettre']],
  ['Pompier', ['feu', 'camion', 'éteindre']],
  ['Réveil', ['matin', 'sonner', 'dormir']],
  ['Lunettes', ['voir', 'nez', 'verres']],
  ['Valise', ['voyage', 'bagage', 'roulettes']],
  ['Jardin', ['fleurs', 'herbe', 'arroser']],
  ['Escalier', ['monter', 'marches', 'étage']],
  ['Marché', ['légumes', 'étals', 'acheter']],
  ['Cinéma', ['film', 'écran', 'pop-corn']],
  ['Dentiste', ['dents', 'carie', 'fauteuil']],
  ['Bougie', ['flamme', 'cire', 'souffler']],
  ['Balcon', ['dehors', 'appartement', 'rambarde']],
  ['Photographe', ['appareil', 'photo', 'objectif']],
  ['Tondeuse', ['herbe', 'jardin', 'couper']],
  ['Aquarium', ['poissons', 'eau', 'verre']],
  ['Grenier', ['maison', 'poussière', 'vieux']],
  ['Passeport', ['voyage', 'identité', 'frontière']],
  ['Serveur', ['restaurant', 'plateau', 'commande']],
  ['Coiffeur', ['cheveux', 'ciseaux', 'couper']],
  ['Zoo', ['animaux', 'cages', 'visiter']],
  ['Autoroute', ['voiture', 'péage', 'vitesse']],
  ['Machine à laver', ['linge', 'tourner', 'lessive']],
  ['Cactus', ['piquant', 'désert', 'plante']],
  ['Trampoline', ['sauter', 'rebondir', 'jardin']],
  ['Karaoké', ['chanter', 'micro', 'écran']],
]

const CELEBRITES = [
  'Zinédine Zidane',
  'Céline Dion',
  'Omar Sy',
  'Jean Dujardin',
  'Marion Cotillard',
  'Kylian Mbappé',
  'Teddy Riner',
  'Édith Piaf',
  'Coluche',
  'Louis de Funès',
  'Brigitte Bardot',
  'Sophie Marceau',
  'Vanessa Paradis',
  'Stromae',
  'Aya Nakamura',
  'Orelsan',
  'Angèle',
  'Squeezie',
  'Jamel Debbouze',
  'Gad Elmaleh',
  'Beyoncé',
  'Rihanna',
  'Michael Jackson',
  'Madonna',
  'Elton John',
  'Freddie Mercury',
  'Leonardo DiCaprio',
  'Brad Pitt',
  'Angelina Jolie',
  'Tom Cruise',
  'Meryl Streep',
  'Will Smith',
  'Keanu Reeves',
  'Scarlett Johansson',
  'Lionel Messi',
  'Cristiano Ronaldo',
  'LeBron James',
  'Serena Williams',
  'Roger Federer',
  'Usain Bolt',
  'Michael Jordan',
  'Albert Einstein',
  'Marie Curie',
  'Napoléon',
  'Cléopâtre',
  'Léonard de Vinci',
  'Pablo Picasso',
  'Mozart',
  'Steve Jobs',
  'Elon Musk',
]

const FILMS = [
  'Titanic',
  'Le Roi Lion',
  'Harry Potter',
  'Star Wars',
  'Le Seigneur des Anneaux',
  'Avatar',
  'Jurassic Park',
  'Matrix',
  'Inception',
  'Interstellar',
  'Forrest Gump',
  'Pulp Fiction',
  'Le Parrain',
  'Retour vers le futur',
  'Les Dents de la mer',
  'E.T.',
  'Rocky',
  'Terminator',
  'Alien',
  'Shining',
  'Intouchables',
  'Le Fabuleux Destin d’Amélie Poulain',
  'Bienvenue chez les Ch’tis',
  'Astérix et Obélix',
  'Les Visiteurs',
  'La Haine',
  'Taxi',
  'OSS 117',
  'Le Dîner de cons',
  'Les Bronzés',
  'La Grande Vadrouille',
  'Ratatouille',
  'Toy Story',
  'Shrek',
  'La Reine des Neiges',
  'Vaiana',
  'Là-haut',
  'Le Monde de Nemo',
  'Les Indestructibles',
  'Aladdin',
  'Kung Fu Panda',
  'Game of Thrones',
  'Breaking Bad',
  'Friends',
  'Stranger Things',
  'The Office',
  'Squid Game',
  'La Casa de Papel',
  'Peaky Blinders',
  'Black Mirror',
]

const CHANSONS = [
  'Ne me quitte pas — Jacques Brel',
  'La vie en rose — Édith Piaf',
  'Formidable — Stromae',
  'Alors on danse — Stromae',
  'Papaoutai — Stromae',
  'Djadja — Aya Nakamura',
  'Dernière danse — Indila',
  'Je veux — Zaz',
  'Balance ton quoi — Angèle',
  'Basique — Orelsan',
  'Bella — Maître Gims',
  'Pour que tu m’aimes encore — Céline Dion',
  'L’aigle noir — Barbara',
  'Mistral gagnant — Renaud',
  'Les Champs-Élysées — Joe Dassin',
  'Aline — Christophe',
  'Comme d’habitude — Claude François',
  'Cette année-là — Claude François',
  'Voyage voyage — Desireless',
  'Joe le taxi — Vanessa Paradis',
  'Ella elle l’a — France Gall',
  'Résiste — France Gall',
  'La Bohème — Charles Aznavour',
  'Emmenez-moi — Charles Aznavour',
  'Bohemian Rhapsody — Queen',
  'Billie Jean — Michael Jackson',
  'Thriller — Michael Jackson',
  'Like a Prayer — Madonna',
  'Rolling in the Deep — Adele',
  'Someone Like You — Adele',
  'Shape of You — Ed Sheeran',
  'Bad Guy — Billie Eilish',
  'Umbrella — Rihanna',
  'Wonderwall — Oasis',
  'Smells Like Teen Spirit — Nirvana',
  'Hotel California — Eagles',
  'Imagine — John Lennon',
  'Yesterday — The Beatles',
  'Let It Be — The Beatles',
  'Africa — Toto',
]

const SPORT = [
  'Football',
  'Basket-ball',
  'Tennis',
  'Natation',
  'Judo',
  'Boxe',
  'Escrime',
  'Handball',
  'Volley-ball',
  'Rugby',
  'Athlétisme',
  'Marathon',
  'Saut à la perche',
  'Lancer de poids',
  'Gymnastique',
  'Patinage artistique',
  'Hockey sur glace',
  'Ski alpin',
  'Snowboard',
  'Surf',
  'Planche à voile',
  'Aviron',
  'Canoë-kayak',
  'Équitation',
  'Golf',
  'Pétanque',
  'Fléchettes',
  'Bowling',
  'Billard',
  'Escalade',
  'Trampoline',
  'Trail',
  'Triathlon',
  'Water-polo',
  'Badminton',
  'Tennis de table',
  'Karaté',
  'Taekwondo',
  'Haltérophilie',
  'Cyclisme',
]

const NOURRITURE = [
  'Croissant',
  'Baguette',
  'Raclette',
  'Fondue savoyarde',
  'Cassoulet',
  'Ratatouille',
  'Bœuf bourguignon',
  'Quiche lorraine',
  'Tartiflette',
  'Blanquette de veau',
  'Steak frites',
  'Croque-monsieur',
  'Crêpe',
  'Gaufre',
  'Macaron',
  'Éclair au chocolat',
  'Mille-feuille',
  'Tarte tatin',
  'Crème brûlée',
  'Profiterole',
  'Pizza',
  'Lasagnes',
  'Risotto',
  'Paella',
  'Sushi',
  'Ramen',
  'Pad thaï',
  'Curry',
  'Couscous',
  'Tajine',
  'Falafel',
  'Houmous',
  'Kebab',
  'Burger',
  'Hot-dog',
  'Tacos',
  'Guacamole',
  'Chili con carne',
  'Cheesecake',
  'Tiramisu',
]

const LIEUX = [
  'Tour Eiffel',
  'Mont Saint-Michel',
  'Château de Versailles',
  'Musée du Louvre',
  'Notre-Dame de Paris',
  'Arc de Triomphe',
  'Mont Blanc',
  'Côte d’Azur',
  'Gorges du Verdon',
  'Dune du Pilat',
  'Cité de Carcassonne',
  'Pont du Gard',
  'Chamonix',
  'Vieux-Port de Marseille',
  'Colisée de Rome',
  'Tour de Pise',
  'Sagrada Família',
  'Big Ben',
  'Statue de la Liberté',
  'Grand Canyon',
  'Times Square',
  'Machu Picchu',
  'Pyramides de Gizeh',
  'Taj Mahal',
  'Grande Muraille de Chine',
  'Mont Fuji',
  'Opéra de Sydney',
  'Christ Rédempteur',
  'Santorin',
  'Venise',
  'Amsterdam',
  'Islande',
  'Sahara',
  'Amazonie',
  'Everest',
  'Chutes du Niagara',
  'Bali',
  'Petra',
  'Stonehenge',
  'Angkor',
]

const EXPRESSIONS = [
  'Avoir le cafard',
  'Poser un lapin',
  'Tomber dans les pommes',
  'Avoir la pêche',
  'Casser les pieds',
  'Mettre les pieds dans le plat',
  'Donner sa langue au chat',
  'Avoir un chat dans la gorge',
  'Il pleut des cordes',
  'Coûter les yeux de la tête',
  'Avoir la tête dans les nuages',
  'En faire tout un fromage',
  'Raconter des salades',
  'Se mettre sur son trente-et-un',
  'Avoir d’autres chats à fouetter',
  'Mettre la main à la pâte',
  'Prendre ses jambes à son cou',
  'Avoir le bras long',
  'Faire la grasse matinée',
  'Être dans de beaux draps',
  'Passer du coq à l’âne',
  'Chercher midi à quatorze heures',
  'Avoir un poil dans la main',
  'Se noyer dans un verre d’eau',
  'Tourner autour du pot',
  'Avoir les yeux plus gros que le ventre',
  'Mettre son grain de sel',
  'Filer à l’anglaise',
  'Avoir la puce à l’oreille',
  'Être tiré à quatre épingles',
  'Rouler sur l’or',
  'Avoir un cœur d’artichaut',
  'Mettre de l’eau dans son vin',
  'Ne pas y aller de main morte',
  'Découvrir le pot aux roses',
]

function build(texts: readonly string[], category: GuessCategory): GuessCard[] {
  return texts.map((text, index) => ({ id: `${category}-${index}`, text, category }))
}

export const GUESS_CARDS: readonly GuessCard[] = [
  ...GENERAL.map(([text, taboo], index) => ({
    id: `general-${index}`,
    text,
    category: 'general' as const,
    taboo: [...taboo],
  })),
  ...build(CELEBRITES, 'celebrites'),
  ...build(FILMS, 'films'),
  ...build(CHANSONS, 'chansons'),
  ...build(SPORT, 'sport'),
  ...build(NOURRITURE, 'nourriture'),
  ...build(LIEUX, 'lieux'),
  ...build(EXPRESSIONS, 'expressions'),
]

export const ALL_CATEGORIES = Object.keys(CATEGORY_LABELS) as GuessCategory[]

export function countByCategory(category: GuessCategory): number {
  return GUESS_CARDS.filter((card) => card.category === category).length
}

export function filterCards(
  categories: readonly GuessCategory[],
  custom: readonly GuessCard[] = [],
): GuessCard[] {
  return [...GUESS_CARDS, ...custom].filter(
    (card) => categories.length === 0 || categories.includes(card.category),
  )
}
